Nschmitt83/relax_mass

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_massage_card_large.scss, app/views/layouts/application.html.erb, app/views/massages/_massage_card_large.html.erb, app/views/massages/_massages_prices.html.erb, app/views/pages/home.html.erb, config/initializers/massage_type.rb
=> Massages cards

app/assets/stylesheets/components/_reviews_details_card.scss, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/_masseur_card_large.html.erb, app/views/masseurs/show.html.erb, app/views/reviews/_reviews_card.html.erb, app/views/reviews/_reviews_details_card.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20190826153757_devise_create_users.rb, db/migrate/20190826155521_create_reviews.rb, db/schema.rb
modif db
create card review and reviews
=> Card review

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_masseur_card.scss, app/assets/stylesheets/components/_rdv_card.scss, app/assets/stylesheets/config/_general.scss, app/controllers/bookings_controller.rb, app/views/bookings/_rdv_card.html.erb, app/views/masseurs/_description_masseur_card.html.erb, app/views/masseurs/show.html.erb, test/controllers/bookings_controller_test.rb
Controller Bookings généré
Card RDV + css
Card description
=> card RDV and card description

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_form_add_booking.scss, app/assets/stylesheets/components/_index.scss, app/controllers/bookings_controller.rb, app/controllers/masseurs_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/bookings/_form_add_booking.html.erb, app/views/layouts/application.html.erb, app/views/masseurs/show.html.erb, app/views/reviews/_reviews_card.html.erb, package.json, test/controllers/bookings_controller_test.rb, yarn.lock
=> Form booking calendar

app/views/massages/_massages_prices.html.erb, app/views/masseurs/show.html.erb, app/views/pages/home.html.erb
Card prices en dynamique sur la show de masseur
=> card price dynamique

app/controllers/masseurs_controller.rb, app/models/review.rb, app/models/user.rb, app/views/masseurs/index.html.erb
logique refiner faite sauf calendrier
=> logique refiner faite sauf calendrier

app/assets/stylesheets/components/_masseur_card.scss, app/controllers/masseurs_controller.rb, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/index.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Search fix (value kept to the index page filters)
Anchors in navbar
Height of Card masseur (css)
=> Refacto faust

app/controllers/bookings_controller.rb, app/views/masseurs/index.html.erb, app/views/masseurs/show.html.erb, db/seeds.rb
=> bugs fixed

app/views/massages/_massage_card_large.html.erb, app/views/pages/home.html.erb, config/initializers/massage_type.rb, db/seeds.rb
=> seeds & photos done

app/controllers/application_controller.rb, app/controllers/massages_controller.rb, app/controllers/profils_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/masseurs/_description_masseur_card.html.erb, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/_masseur_card_large.html.erb, app/views/masseurs/show.html.erb, app/views/profils/_to_become_massotheraps.html.erb, app/views/profils/edit.html.erb, app/views/profils/show.html.erb, app/views/reviews/_reviews_card.html.erb, config/initializers/massage_type.rb, config/routes.rb, test/controllers/massages_controller_test.rb
Form user become a masseur
Controller and View profile masseur
=> form and profile new massoterapeute

app/controllers/masseurs_controller.rb, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/show.html.erb, app/views/pages/home.html.erb
il reste à faire persister la date depuis l'index
> voir le flatpicker
=> persistence préselection type massage depuis refiner ou search de la home

db/seeds.rb
Added SIRET random number to seeds of masseurs
=> seed siret to masseurs

app/controllers/bookings_controller.rb, app/controllers/masseurs_controller.rb, app/controllers/profils_controller.rb, app/views/profils/edit.html.erb, db/seeds.rb
random sur les seeds siret retiré
=> Seeds siret

app/controllers/bookings_controller.rb, app/controllers/masseurs_controller.rb, app/controllers/profils_controller.rb, app/views/profils/edit.html.erb
delete email field
limit of caracters for siret
field massage type required
type of file upload required
=> form inscription evolutions

app/controllers/bookings_controller.rb, app/controllers/masseurs_controller.rb, app/controllers/profils_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/available_hours.js, app/javascript/plugins/flatpickr.js, app/javascript/plugins/stripe.js, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/show.html.erb
=> Hour select

app/assets/stylesheets/pages/_home.scss, app/views/masseurs/show.html.erb, app/views/pages/home.html.erb, app/views/profils/show.html.erb, app/views/reviews/_reviews_card.html.erb, app/views/reviews/_reviews_details_card.html.erb, app/views/shared/_footer.html.erb, db/seeds.rb
Dans cette branche :
> seeds changées
> btn add review et mailto
> btn localiser
> open des réseaux sociaux dans une autre page
=> quick fix et btn done

app/views/profils/_card_planning.html.erb, app/views/profils/show.html.erb, app/views/reviews/_reviews_card.html.erb
Added Planning card show profil when masseur
Debug Reviews card show profil when masseur
=>  bug fix show profil rdv

app/assets/stylesheets/components/_navbar.scss, app/views/bookings/new.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
bugs suivants fixés : 
> navbar en responsive sur mobile
> centrage texte page checkout
=> Frontbugfix

app/models/user.rb, app/views/masseurs/_masseur_card.html.erb, app/views/masseurs/_masseur_card_large.html.erb, app/views/profils/edit.html.erb
Fix of notations filter on index (rating not nil)
Fix of SIRET maxlength
=> bug fix notations filter and SIRET length

db/seeds.rb
=> image seed michel h
